name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    - run: npm ci

    - name: Run Tests with Vitest
      run: npx vitest run

    - name: Build app
      run: npm run build
      
    - name: Copy build to root folder
      run: |
        mkdir -p build-artifacts
        cp -r dist/* build-artifacts/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-build
        path: dist/

    - name: Read and bump version
      id: bump-version
      run: |
        version=$(cat VERSION)
        echo "Current version: $version"
        major=$(echo $version | cut -d. -f1 | tr -d v)
        minor=$(echo $version | cut -d. -f2)
        patch=$(echo $version | cut -d. -f3)

        new_patch=$((patch + 1))
        new_version="v$major.$minor.$new_patch"

        echo "$new_version" > VERSION
        echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
        echo "New version: $new_version"

    - name: Commit and push new VERSION file
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git commit -am
