name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    - run: npm ci

    - name: Run Tests with Vitest
      run: npx vitest run

    - name: Build app
      run: npm run build
      
    - name: Copy build to root folder
      run: |
        mkdir -p build-artifacts
        cp -r dist/* build-artifacts/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-build
        path: dist/

    - name: Read and bump version from package.json
      id: bump-version
      run: |
        version=$(node -p "require('./package.json').version")
        echo "Current version: $version"
        
        # Increment patch version (you can change this logic to handle minor/major if required)
        major=$(echo $version | cut -d. -f1)
        minor=$(echo $version | cut -d. -f2)
        patch=$(echo $version | cut -d. -f3)
        
        new_patch=$((patch + 1))
        new_version="$major.$minor.$new_patch"

        # Update package.json with the new version
        jq --arg version "$new_version" '.version = $version' package.json > temp.json && mv temp.json package.json
        
        echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
        echo "New version: $new_version"

    - name: Commit and push new version in package.json
      run: |
        git config user.name "Electrify-Services"
        git config user.email "software.development@electrifyservices.com"
        git add package.json
        git commit -am "chore: bump version to $NEW_VERSION"
        git tag $NEW_VERSION
        git push origin main --tags

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: "electrify1"
        password: "qwertyuiop12"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image with version
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          electrify1/test-github-action:latest
          electrify1/test-github-action:${{ env.NEW_VERSION }}
